//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderMealEntities : DbContext
    {
        public OrderMealEntities()
            : base("name=OrderMealEntities")
        {
            // Get the ObjectContext related to this DbContext             
            var objectContext = ((System.Data.Entity.Infrastructure.IObjectContextAdapter)this).ObjectContext;
            // Sets the command timeout for all the commands             
            objectContext.CommandTimeout =2 * 60;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<foods> foods { get; set; }
        public virtual DbSet<goods> goods { get; set; }
        public virtual DbSet<ratings> ratings { get; set; }
        public virtual DbSet<RatingsSellers> RatingsSellers { get; set; }
        public virtual DbSet<sellers> sellers { get; set; }
        public virtual DbSet<supports> supports { get; set; }
        public virtual DbSet<Token> Token { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<OrderDetailsInfo> OrderDetailsInfo { get; set; }
        public virtual DbSet<OrderInfo> OrderInfo { get; set; }
    }
}
