//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailsInfo
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int GoodId { get; set; }
        public string GoodName { get; set; }
        public int FoodId { get; set; }
        public string FoodName { get; set; }
        public int Count { get; set; }
        public decimal AmountTotal { get; set; }
        public decimal AmountDiscount { get; set; }
        public decimal AmountReal { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public string image { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
