//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public int Id { get; set; }
        public string OrderNum { get; set; }
        public string transactionId { get; set; }
        public decimal Amount { get; set; }
        public int SellerId { get; set; }
        public string SellerName { get; set; }
        public int PayWay { get; set; }
        public System.DateTime BookTime { get; set; }
        public int CusCount { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> DeskNumber { get; set; }
        public int Status { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public string avatar { get; set; }
        public Nullable<decimal> AmountDiscount { get; set; }
        public Nullable<decimal> AmountReal { get; set; }
    }
}
