//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingsSellers
    {
        public int Id { get; set; }
        public Nullable<int> sellerId { get; set; }
        public string username { get; set; }
        public string rateTime { get; set; }
        public string deliveryTime { get; set; }
        public Nullable<decimal> score { get; set; }
        public Nullable<int> rateType { get; set; }
        public string text { get; set; }
        public string avatar { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<decimal> rateTaste { get; set; }
        public Nullable<decimal> rateService { get; set; }
        public Nullable<decimal> rateComfortLevel { get; set; }
    }
}
