//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        public int Id { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> oldPrice { get; set; }
        public string description { get; set; }
        public Nullable<int> sellCount { get; set; }
        public Nullable<int> rating { get; set; }
        public string info { get; set; }
        public string icon { get; set; }
        public string image { get; set; }
        public int DelFlag { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
