//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vue.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderMealEntities : DbContext
    {
        public OrderMealEntities()
            : base("name=OrderMealEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<food> foods { get; set; }
        public virtual DbSet<good> goods { get; set; }
        public virtual DbSet<rating> ratings { get; set; }
        public virtual DbSet<seller> sellers { get; set; }
        public virtual DbSet<support> supports { get; set; }
    }
}
