//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seller
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int deliveryTime { get; set; }
        public int score { get; set; }
        public int serviceScore { get; set; }
        public int foodScore { get; set; }
        public int rankRate { get; set; }
        public decimal minPrice { get; set; }
        public decimal deliveryPrice { get; set; }
        public int ratingCount { get; set; }
        public int sellCount { get; set; }
        public string bulletin { get; set; }
        public string avatar { get; set; }
        public int DelFlag { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
